DROP IF EXISTS ODONTOLOGOS;
CREATE TABLE IF NOT EXISTS ODONTOLOGOS (
    NUMEROMATRICULA INT AUTOINCREMENT PRIMARY KEY  INT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL
);

INSERT INTO ODONTOLOGOS (NUMEROMATRICULA, NOMBRE, APELLIDO) VALUES (1, 'Juan', 'Perez');
INSERT INTO ODONTOLOGOS (NUMEROMATRICULA, NOMBRE, APELLIDO) VALUES (2, 'Maria', 'Gomez');